#pragma once

#include <pebble.h>

// Margins and spacing
#define LAYOUT_MARGIN 8
#define LAYOUT_BASE_MARGIN PBL_IF_ROUND_ELSE(4, 8)
#define LAYOUT_GPS_ARROW_TEXT_SPACING 4
#define LAYOUT_GPS_ARROW_POSITION_ADJUST -1
#define LAYOUT_MAP_MARGIN PBL_IF_ROUND_ELSE(10, -10)
#define LAYOUT_ROUND_CITY_MARGIN_RESTORE 4
#define LAYOUT_ROUND_CITY_FRAME_ADJUST -1

// Map
#define LAYOUT_WORLD_MAP_BOTTOM_TRIM 10
#define LAYOUT_WORLD_MAP_TOP PBL_IF_ROUND_ELSE(45, STATUS_BAR_LAYER_HEIGHT)
#define LAYOUT_FALLBACK_MAP_HEIGHT 72

// City dot
#define LAYOUT_CITY_DOT_RADIUS 4

// Ruler
#define LAYOUT_RULER_LINE_Y_OFFSET 11
#define LAYOUT_RULER_LAYER_HEIGHT 20

// Vertical offsets from map bottom
#define LAYOUT_CITY_Y_OFFSET PBL_IF_ROUND_ELSE(4, 5)
#define LAYOUT_RULER_Y_OFFSET PBL_IF_ROUND_ELSE(13, 22)
#define LAYOUT_TIME_Y_OFFSET PBL_IF_ROUND_ELSE(22, 31)
#define LAYOUT_RELATIVE_INFO_Y_OFFSET PBL_IF_ROUND_ELSE(64, 73)

// GPS arrow
#define LAYOUT_GPS_ARROW_WIDTH 12
#define LAYOUT_GPS_ARROW_HEIGHT 14

// City text
#define LAYOUT_CITY_LAYER_HEIGHT 30
#if defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_CITY_FONT_HEIGHT 24
#else
#define LAYOUT_CITY_FONT_HEIGHT 18
#endif

// Time display
#define LAYOUT_TIME_LAYER_HEIGHT 40

// AM/PM
#define LAYOUT_AMPM_LAYER_WIDTH 40
#define LAYOUT_AMPM_LAYER_HEIGHT 20
#define LAYOUT_AMPM_Y_FROM_TIME_TOP 8
#define LAYOUT_AMPM_X_OFFSET 0
#define LAYOUT_AMPM_Y_OFFSET 12

// Relative info
#define LAYOUT_RELATIVE_INFO_LAYER_HEIGHT 19

// Status bar
#define LAYOUT_STATUSBAR_MARGIN PBL_IF_ROUND_ELSE(8, 8)
#define LAYOUT_STATUSBAR_Y_COMPENSATION -1

// Font compensators
#define LAYOUT_FONT_COMPENSATOR_LECO_38 3
#define LAYOUT_FONT_COMPENSATOR_DEFAULT 1

// Fonts
#if defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_FONT_CITY FONT_KEY_GOTHIC_24_BOLD
#define LAYOUT_FONT_RELATIVE_INFO FONT_KEY_GOTHIC_18
#define LAYOUT_FONT_STATUSBAR FONT_KEY_GOTHIC_18
#else
#define LAYOUT_FONT_CITY FONT_KEY_GOTHIC_18_BOLD
#define LAYOUT_FONT_RELATIVE_INFO FONT_KEY_GOTHIC_14
#define LAYOUT_FONT_STATUSBAR FONT_KEY_GOTHIC_14
#endif

#define LAYOUT_FONT_TIME FONT_KEY_LECO_38_BOLD_NUMBERS
#define LAYOUT_FONT_AMPM FONT_KEY_LECO_26_BOLD_NUMBERS_AM_PM

// Font compensators (must match font sizes above)
#if defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_FONT_COMPENSATOR_CITY 3
#else
#define LAYOUT_FONT_COMPENSATOR_CITY 1
#endif

// Scroll animations
#define LAYOUT_SCROLL_DURATION_MS 260
#define LAYOUT_BACKGROUND_SCROLL_DURATION_MS 200
#define LAYOUT_SCROLL_DIST_OUT 20
#define LAYOUT_SCROLL_DIST_IN 8
#define LAYOUT_DOT_ANIMATION_DURATION_MS 300
