#pragma once

#include <pebble.h>

// Colors
#define COLOR_MAP_FOREGROUND PBL_IF_COLOR_ELSE(GColorWhite, GColorWhite)
#define COLOR_MAP_BACKGROUND                                                   \
  PBL_IF_COLOR_ELSE(GColorPictonBlue, GColorLightGray)
#define COLOR_MAP_NIGHT_FOREGROUND                                             \
  PBL_IF_COLOR_ELSE(GColorLightGray, GColorLightGray)
#define COLOR_MAP_NIGHT_BACKGROUND                                             \
  PBL_IF_COLOR_ELSE(GColorBlueMoon, GColorBlack)
#define COLOR_MAP_NIGHT_OVERLAY PBL_IF_COLOR_ELSE(GColorBlack, GColorLightGray)
#define COLOR_CROSSHAIR GColorBlack
#define COLOR_DOT_FILL PBL_IF_COLOR_ELSE(GColorChromeYellow, GColorWhite)
#define COLOR_DOT_OUTLINE GColorBlack
#define COLOR_TEXT_DEFAULT GColorBlack
#define COLOR_RULER GColorBlack
#define COLOR_STATUSBAR_TEXT GColorBlack
#define COLOR_APP_BACKGROUND PBL_IF_COLOR_ELSE(GColorPictonBlue, GColorWhite)

#define COLOR_TEXT_DEFAULT_NIGHT GColorWhite
#define COLOR_CROSSHAIR_NIGHT PBL_IF_COLOR_ELSE(GColorBlack, GColorWhite)
#define COLOR_DOT_FILL_NIGHT PBL_IF_COLOR_ELSE(GColorChromeYellow, GColorWhite)
#define COLOR_DOT_FILL PBL_IF_COLOR_ELSE(GColorChromeYellow, GColorWhite)
#define COLOR_DOT_OUTLINE_NIGHT GColorBlack
#define COLOR_STATUSBAR_TEXT_NIGHT GColorWhite
#define COLOR_RULER_NIGHT GColorWhite
#define COLOR_APP_BACKGROUND_NIGHT                                             \
  PBL_IF_COLOR_ELSE(GColorBlueMoon, GColorBlack)

// Margins and spacing
#define LAYOUT_MARGIN 8
#if defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_BASE_MARGIN 20
#elif defined(PBL_PLATFORM_CHALK)
#define LAYOUT_BASE_MARGIN 14
#else
#define LAYOUT_BASE_MARGIN 8
#endif
#if defined(PBL_PLATFORM_GABBRO) || defined(PBL_PLATFORM_EMERY)
#define LAYOUT_GPS_ARROW_POSITION_ADJUST 2
#define LAYOUT_GPS_ARROW_TEXT_SPACING 2
#else
#define LAYOUT_GPS_ARROW_POSITION_ADJUST -1
#define LAYOUT_GPS_ARROW_TEXT_SPACING 4
#endif
#define LAYOUT_MAP_MARGIN 0
#define LAYOUT_ROUND_CITY_MARGIN_RESTORE 4
#define LAYOUT_ROUND_CITY_FRAME_ADJUST -1

// Map
#define LAYOUT_WORLD_MAP_BOTTOM_TRIM 10
#if defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_WORLD_MAP_TOP 31
#elif defined(PBL_PLATFORM_CHALK)
#define LAYOUT_WORLD_MAP_TOP 20
#else
#define LAYOUT_WORLD_MAP_TOP STATUS_BAR_LAYER_HEIGHT
#endif
#define LAYOUT_FALLBACK_MAP_HEIGHT 72
#if defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_WORLD_MAP_CROP 4
#else
#define LAYOUT_WORLD_MAP_CROP 3
#endif

// City dot
#define LAYOUT_CITY_DOT_RADIUS 3

// Ruler
#define LAYOUT_RULER_LINE_Y_OFFSET 11
#define LAYOUT_RULER_LAYER_HEIGHT 20

// Vertical offsets from map bottom
#if defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_CITY_Y_OFFSET 3
#define LAYOUT_RULER_Y_OFFSET 25
#define LAYOUT_TIME_Y_OFFSET 33
#define LAYOUT_RELATIVE_INFO_Y_OFFSET 77
#define LAYOUT_TIME_AM_PM_Y_OFFSET 16
#elif defined(PBL_PLATFORM_EMERY)
#define LAYOUT_CITY_Y_OFFSET 5
#define LAYOUT_RULER_Y_OFFSET 30
#define LAYOUT_TIME_Y_OFFSET 41
#define LAYOUT_RELATIVE_INFO_Y_OFFSET 88
#define LAYOUT_TIME_AM_PM_Y_OFFSET 16
#elif defined(PBL_PLATFORM_CHALK)
#define LAYOUT_CITY_Y_OFFSET 1
#define LAYOUT_RULER_Y_OFFSET 13
#define LAYOUT_TIME_Y_OFFSET 19
#define LAYOUT_RELATIVE_INFO_Y_OFFSET 57
#define LAYOUT_TIME_AM_PM_Y_OFFSET 12
#else
#define LAYOUT_CITY_Y_OFFSET 5
#define LAYOUT_RULER_Y_OFFSET 21
#define LAYOUT_TIME_Y_OFFSET 31
#define LAYOUT_RELATIVE_INFO_Y_OFFSET 73
#define LAYOUT_TIME_AM_PM_Y_OFFSET 12
#endif
// GPS arrow
#define LAYOUT_GPS_ARROW_WIDTH 12
#define LAYOUT_GPS_ARROW_HEIGHT 14

// City text
#define LAYOUT_CITY_LAYER_HEIGHT 30
#if defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_CITY_FONT_HEIGHT 24
#else
#define LAYOUT_CITY_FONT_HEIGHT 18
#endif

// Time display
#if defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_TIME_LAYER_HEIGHT 46
#define LAYOUT_TIME_AM_PM_LAYER_HEIGHT 46
#define LAYOUT_TIME_AM_PM_SPACING 2
#else
#define LAYOUT_TIME_LAYER_HEIGHT 40
#define LAYOUT_TIME_AM_PM_LAYER_HEIGHT 40
#define LAYOUT_TIME_AM_PM_SPACING 1
#endif
#define LAYOUT_TIME_AM_PM_LAYER_WIDTH 40

// Relative info
#define LAYOUT_RELATIVE_INFO_LAYER_HEIGHT 19

// Status bar
#if defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_STATUSBAR_MARGIN 16
#define LAYOUT_STATUSBAR_Y_COMPENSATION 5
#else
#define LAYOUT_STATUSBAR_MARGIN 8
#define LAYOUT_STATUSBAR_Y_COMPENSATION -1
#endif

// Font compensators
#define LAYOUT_FONT_COMPENSATOR_LECO_38 3
#define LAYOUT_FONT_COMPENSATOR_DEFAULT 1

// Fonts
#if defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_FONT_CITY FONT_KEY_GOTHIC_24_BOLD
#define LAYOUT_FONT_RELATIVE_INFO FONT_KEY_GOTHIC_18
#define LAYOUT_FONT_STATUSBAR FONT_KEY_GOTHIC_18
#else
#define LAYOUT_FONT_CITY FONT_KEY_GOTHIC_18_BOLD
#define LAYOUT_FONT_RELATIVE_INFO FONT_KEY_GOTHIC_14
#define LAYOUT_FONT_STATUSBAR FONT_KEY_GOTHIC_14
#endif

#if defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_FONT_TIME FONT_KEY_LECO_42_NUMBERS
#define LAYOUT_FONT_TIME_AM_PM FONT_KEY_LECO_26_BOLD_NUMBERS_AM_PM
#else
#define LAYOUT_FONT_TIME FONT_KEY_LECO_38_BOLD_NUMBERS
#define LAYOUT_FONT_TIME_AM_PM FONT_KEY_LECO_26_BOLD_NUMBERS_AM_PM
#endif

// Font compensators (must match font sizes above)
#if defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO)
#define LAYOUT_FONT_COMPENSATOR_CITY 3
#else
#define LAYOUT_FONT_COMPENSATOR_CITY 1
#endif

// Scroll animations
#define LAYOUT_SCROLL_DURATION_MS 260
#define LAYOUT_BACKGROUND_SCROLL_DURATION_MS 200
#define LAYOUT_SCROLL_DIST_OUT 20
#define LAYOUT_SCROLL_DIST_IN 8
#define LAYOUT_DOT_ANIMATION_DURATION_MS 300
